import { chromium, expect as baseExpect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

const expect = baseExpect.configure({ timeout: 30000 });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
// This test never contacts a real lead or external service.
await context.route('**/*', route => /^https?:\/\/(127\.0\.0\.1|localhost)(:|\/)/.test(route.request().url()) ? route.continue() : route.abort());
const page = await context.newPage();
page.setDefaultTimeout(30000);
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await mkdir('test-results', { recursive: true });
try {
  await page.goto('http://127.0.0.1:5174/#/companies/1/show', { waitUntil: 'domcontentloaded', timeout: 120000 });
  await expect(page.getByRole('button', { name: 'No answer', exact: true })).toBeEnabled();
  await page.getByLabel('Use one sentence based on observed facts, up to 25 words.').fill('Who answers your website enquiries after hours?');
  await page.getByRole('button', { name: 'Save first line', exact: true }).click();
  await expect(page.getByText('First line saved', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Research', exact: true }).click();
  await page.getByRole('checkbox', { name: /Unverified/ }).click();
  await expect(page.getByRole('checkbox', { name: 'Verified by human', exact: true })).toBeChecked();
  await page.getByRole('tab', { name: 'Summary', exact: true }).click();
  await page.getByRole('button', { name: 'No answer', exact: true }).click();
  await expect(page.getByText('Call outcome saved', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Tests', exact: true }).click();
  await page.getByRole('button', { name: 'Add enquiry test', exact: true }).click();
  await page.getByLabel('What was sent or done').fill('Asked when the office is open.');
  await page.getByLabel('Sent at', { exact: true }).fill('2026-09-27T10:00');
  await page.getByLabel('Replied at (leave blank if no reply)').fill('2026-09-27T13:12');
  await page.getByLabel('Observed facts', { exact: true }).fill('Received opening hours after 3 hours and 12 minutes.');
  await page.getByRole('button', { name: 'Save test', exact: true }).click();
  await expect(page.getByText('3h 12m', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Move to Tested', exact: true }).click();
  const nudge = page.getByRole('dialog');
  await expect(nudge.getByRole('heading', { name: 'What’s the next step, and when?' })).toBeVisible();
  await nudge.getByLabel('Next step', { exact: true }).fill('Call the owner');
  await nudge.getByLabel('When (your local time)').fill('2026-10-01T10:00');
  await nudge.getByRole('button', { name: 'Save next step' }).click();
  await expect(page.getByText('Next step saved', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Edit test', exact: true }).click();
  await page.getByLabel('Reply summary').fill('Opening hours confirmed');
  await page.getByRole('button', { name: 'Save test', exact: true }).click();
  await expect(page.getByText('Reply: Opening hours confirmed')).toBeVisible();
  await page.getByRole('tab', { name: 'Summary', exact: true }).click();
  // Log the first WhatsApp open; all remote navigation is intercepted above.
  const popupPromise = context.waitForEvent('page');
  await page.getByRole('button', { name: 'WhatsApp', exact: true }).click();
  const popup = await popupPromise;
  await expect(page.getByText('1 opens today · India time')).toBeVisible();
  await popup.close();
  await page.getByRole('button', { name: 'WhatsApp', exact: true }).click();
  await expect(page.getByRole('alert').filter({ hasText: 'Your number was restricted' })).toBeVisible();
  await expect(page.getByText('Last chat opened less than 12 minutes ago')).toBeVisible();
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(page.getByRole('button', { name: 'No answer', exact: true })).toBeEnabled();
  await page.getByRole('tab', { name: 'Research', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Research', exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/demo-company-desktop.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('link', { name: 'Businesses', exact: true }).click();
  await page.getByRole('button', { name: 'Upload list', exact: true }).click();
  await page.getByLabel('Choose CSV file').setInputFiles({ name: 'leads.csv', mimeType: 'text/csv', buffer: Buffer.from('name,city,website,phone,state\nAAA Test Lead,Dallas,https://test-lead.example,+12025550199,TX\nAAA Test Duplicate,Dallas,https://test-lead.example/path,+12025550199,TX\n') });
  await expect(page.getByText('Added 1, skipped 1 duplicates')).toBeVisible();
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await expect(page.getByRole('link').filter({ hasText: 'AAA Test Lead' })).toBeVisible();
  await page.getByRole('link').filter({ hasText: 'AAA Test Lead' }).click();
  await page.getByRole('tab', { name: 'Research', exact: true }).click();
  await expect(page.getByText('Waiting for research', { exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Summary', exact: true }).click();
  await expect(page.getByRole('button', { name: 'No answer', exact: true })).toBeEnabled();
  await page.setViewportSize({ width: 375, height: 812 });
  await expect(page.getByText('First line', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'No answer', exact: true })).toBeEnabled();
  const companyWidth = await page.evaluate(() => ({ viewport: innerWidth, content: document.documentElement.scrollWidth }));
  if (companyWidth.content > companyWidth.viewport) throw new Error('Company page overflows on phone: ' + JSON.stringify(companyWidth));
  await page.screenshot({ path: 'test-results/demo-company-mobile.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('link', { name: 'Leads', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Found', exact: true })).toBeVisible();
  await expect(page.getByText('AAA Test Lead').first()).toBeVisible();
  const board = page.locator('.overflow-x-auto').filter({ has: page.getByRole('heading', { name: 'Found', exact: true }) });
  const widths = await board.evaluate(element => ({ visible: element.clientWidth, scroll: element.scrollWidth }));
  if (widths.scroll <= widths.visible) throw new Error('Board is not horizontally scrollable');
  const boardWidth = await page.evaluate(() => ({ viewport: innerWidth, content: document.documentElement.scrollWidth }));
  if (boardWidth.content > boardWidth.viewport) throw new Error('Board page overflows: ' + JSON.stringify(boardWidth));
  await page.screenshot({ path: 'test-results/demo-board-mobile.png', fullPage: true, animations: 'disabled' });
  if (errors.length) throw new Error(errors.join('\n'));
  console.log('PASS: research verification, first line, call, enquiry add/edit, stage nudge/task, WhatsApp warning, duplicate CSV upload, 375px company and board. No page errors.');
} finally { await browser.close(); }
