alter table public.companies
    add column external_key text unique,
    add column research_status text not null default 'to_research' check (research_status in ('to_research','researching','done','failed')),
    add column research jsonb,
    add column first_line text,
    add column score smallint,
    add column timezone text,
    add column source text,
    add column business_type text;

create table public.enquiry_tests (
    id bigint generated by default as identity primary key,
    company_id bigint not null references public.companies(id) on delete cascade,
    channel text not null check (channel in ('web_form','phone','email','chat','whatsapp','marketplace','other')),
    what_sent text not null,
    sent_at timestamptz not null,
    replied_at timestamptz,
    reply_summary text,
    observed text,
    sales_id bigint references public.sales(id),
    created_at timestamptz not null default now()
);
create table public.call_logs (
    id bigint generated by default as identity primary key,
    company_id bigint not null references public.companies(id) on delete cascade,
    contact_id bigint references public.contacts(id) on delete set null,
    outcome text not null check (outcome in ('no_answer','voicemail','gatekeeper','spoke_owner','booked','not_interested','wrong_number')),
    note text,
    called_at timestamptz not null default now(),
    sales_id bigint references public.sales(id)
);
create table public.whatsapp_opens (
    id bigint generated by default as identity primary key,
    company_id bigint not null references public.companies(id) on delete cascade,
    opened_at timestamptz not null default now(),
    sales_id bigint references public.sales(id)
);
create index enquiry_tests_company_id_idx on public.enquiry_tests(company_id);
create index call_logs_company_id_idx on public.call_logs(company_id);
create index whatsapp_opens_company_id_idx on public.whatsapp_opens(company_id);
create index whatsapp_opens_opened_at_idx on public.whatsapp_opens(opened_at);

alter table public.enquiry_tests enable row level security;
create policy "Enable read access for authenticated users" on public.enquiry_tests for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.enquiry_tests for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.enquiry_tests for update to authenticated using (true) with check (true);
create policy "Enable delete for authenticated users only" on public.enquiry_tests for delete to authenticated using (true);

alter table public.call_logs enable row level security;
create policy "Enable read access for authenticated users" on public.call_logs for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.call_logs for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.call_logs for update to authenticated using (true) with check (true);
create policy "Enable delete for authenticated users only" on public.call_logs for delete to authenticated using (true);

alter table public.whatsapp_opens enable row level security;
create policy "Enable read access for authenticated users" on public.whatsapp_opens for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.whatsapp_opens for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.whatsapp_opens for update to authenticated using (true) with check (true);
create policy "Enable delete for authenticated users only" on public.whatsapp_opens for delete to authenticated using (true);
create or replace view public.companies_summary with (security_invoker = on) as
select
    c.id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.sales_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    count(distinct d.id) as nb_deals,
    count(distinct co.id) as nb_contacts,
    c.external_key, c.research_status, c.research, c.first_line,
    c.score, c.timezone, c.source, c.business_type
from public.companies c
    left join public.deals d on c.id = d.company_id
    left join public.contacts co on c.id = co.company_id
group by c.id;


-- Precedence is overdue, stale, no next step; recently created deals cannot be stale.
create or replace view public.deal_health with (security_invoker = on) as
select h.*, case
    when h.stage in ('won','lost') then 'ok'
    when h.next_task_due < now() then 'overdue'
    when h.created_at < now() - interval '7 days'
      and h.last_touch_at < now() - interval '7 days' then 'stale'
    when h.open_task_count = 0 then 'no_next_step'
    else 'ok'
end as state
from (
    select d.id, d.company_id, d.stage, d.created_at,
      greatest(d.updated_at, d.created_at,
        (select max(n.date) from public.deal_notes n where n.deal_id = d.id),
        (select max(n.date) from public.contact_notes n join public.contacts c on c.id = n.contact_id where c.company_id = d.company_id),
        (select max(l.called_at) from public.call_logs l where l.company_id = d.company_id),
        (select max(w.opened_at) from public.whatsapp_opens w where w.company_id = d.company_id),
        (select max(greatest(e.sent_at, e.replied_at)) from public.enquiry_tests e where e.company_id = d.company_id),
        (select max(t.done_date) from public.tasks t join public.contacts c on c.id = t.contact_id where c.company_id = d.company_id)
      ) as last_touch_at,
      (select min(t.due_date) from public.tasks t join public.contacts c on c.id = t.contact_id where c.company_id = d.company_id and t.done_date is null) as next_task_due,
      (select count(*) from public.tasks t join public.contacts c on c.id = t.contact_id where c.company_id = d.company_id and t.done_date is null) as open_task_count
    from public.deals d
) h;

revoke all on public.enquiry_tests from anon;
grant select, insert, update, delete on public.enquiry_tests to authenticated;
grant all on public.enquiry_tests to service_role;
grant usage, select on sequence public.enquiry_tests_id_seq to authenticated, service_role;

revoke all on public.call_logs from anon;
grant select, insert, update, delete on public.call_logs to authenticated;
grant all on public.call_logs to service_role;
grant usage, select on sequence public.call_logs_id_seq to authenticated, service_role;

revoke all on public.whatsapp_opens from anon;
grant select, insert, update, delete on public.whatsapp_opens to authenticated;
grant all on public.whatsapp_opens to service_role;
grant usage, select on sequence public.whatsapp_opens_id_seq to authenticated, service_role;

grant select on public.deal_health to authenticated, service_role;
revoke all on public.deal_health from anon;
